project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: 
    - repo: https://github.com/professorwug/professorwug.github.io

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  ieee-pdf: default

execute:
  freeze: auto



