project:
  type: manuscript

manuscript:
  article: index.qmd
  code-links: repo
      

format:
  html:
    toc: true
    comments:
      hypothesis: true
  jats: default

  # (other formats)
  ieee-pdf: default

execute:
  freeze: auto



