project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  ieee-pdf: default

execute:
  freeze: auto



